### ISSUE TITLE
[BUG] Codacy scan fingerprint mismatch

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms#156]
**Describe the bug**
The codacy scan is failing on a test base.py which uses mocks.
I believe it is failing because the mock call fingerprint would be different from run to run.

I propose removing the base.py from the codacy scan.
```
on:
  push:
    branches: [main, protected]
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'tests/tools/base.py'
```

See (https://github.com/kyegomez/swarms/actions/runs/6910593843/job/18803966896?pr=155) for an example of the failing run.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/156">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/156/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/156/pledge.svg">
</picture>
</a>
