### ISSUE TITLE
[BUG] Context Length Exceeded Error in Swarms CLI with Agent Creation

### ISSUE THREAD

**Issue by chethanuk** [kyegomez/swarms#746]
When running the `swarms run-agents` command, users are encountering a context length exceeded error with GPT-4. The error occurs during agent creation and execution, specifically when trying to process system prompts and tasks.

**Error Message**
```
litellm.ContextWindowExceededError: litellm.BadRequestError: ContextWindowExceededError: 
OpenAIException - Error code: 400 - {"error": {"message": "This model's maximum context length is 8192 tokens. However, you requested 8492 tokens (4492 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.", "type": "invalid_request_error", "param": "messages", "code": "context_length_exceeded"}}
```

**Reproduction Steps**
1. Create an `agents.yaml` with multiple agents
2. Configure agents with system prompts and tasks
3. Run `swarms run-agents --yaml-file agents.yaml`

**Current Configuration**
```yaml
agents:
  - agent_name: "Financial-Analysis-Agent"
    model:
      model_name: "gpt-4"
      temperature: 0.1
      max_tokens: 2000
    system_prompt: "financial_agent_sys_prompt"
    max_loops: 1
    context_length: 4000
    # ... other settings

  - agent_name: "Stock-Analysis-Agent"
    model:
      model_name: "gpt-4"
      temperature: 0.2
      max_tokens: 1500
    system_prompt: "stock_agent_sys_prompt"
    max_loops: 2
    context_length: 4000
    # ... other settings
```

Action Items:
- Add guidelines for token limits
- Calculate actual token count before sending to API [If we use Model Router change model accordingly in retry]
